Feat/new mecanic
cnumr/ecoindex_badge pull request #14
Opened 2023-03-21 11:25 UTC by hrenaud

Tout est changé 
- Dessin du bouton, plus de SVG ;
- Meilleure accessibilité ;
- Appel de l'API pour récupérer la mesure et dessiner le bouton ;
- Si la page n'a pas encore été mesurée, le bouton propose de le faire et au retour, se redessine ;
- Si sur mobile, c'est au deuxième tap que la page est mesurée.

Code bcp plus complexe, mais plus de SVG et interaction possible directement depuis le bouton.

2023-03-21 12:44 UTC, jpkha requested changes

2023-03-21 12:44 UTC, jpkha commented on assets/js/ecoindex-badge.js
> +          font-size: 12px;
Si on met la font-size en 12px, autant tout mettre en px ou en tous cas avoir une uniformité dans les unites utilisées ?

2023-03-21 12:46 UTC, jpkha commented on assets/js/ecoindex-badge.js
> +        badgeElement = document.createElement(`div`);
Ok je viens de lire/voir que tu as fait une fonctionnalité pour ce cas.
Je vais tester en local, j'ai juste fait une review rapide

2023-03-21 12:48 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +<html>
oups, j'ai trop mis de code, je vais épurer

2023-03-21 13:04 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +<html>
c'est fait

2023-03-21 13:04 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +      // const url = `htts://novagaia.fr/`;
c'est fait

2023-03-21 13:04 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +          background-color: ${theme === `light` ? `#FFF` : `#000`};
c'est fait

2023-03-21 13:04 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +          font-size: 12px;
c'est fait

2023-03-21 13:06 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +        gradeElement.setAttribute(`aria-label`, `Note inconnue`);
c'est fait

2023-03-21 13:07 UTC, vvatelot commented on assets/js/ecoindex-badge.js
> +        badgeElement = document.createElement(`div`);
Est ce que ça ne fait pas un peu trop grand ? :thinking:

2023-03-21 13:07 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +        badgeElement = document.createElement(`div`);
Normalement c'est bon, tu clics et ça relance le fetch en mode POST pour lancer la mesure et quand c'est OK, je composant est supprimé et est redessiné avec le résultat.

2023-03-21 13:09 UTC, vvatelot commented
Est ce que en description de la PR tu pourrais mettre des screenshots de ce que ça donne maintenant ? :)

2023-03-21 13:59 UTC, jpkha commented on assets/js/ecoindex-badge.js
> +        badgeElement = document.createElement(`div`);
Je pense qu'il faut essayer de reprendre la phrase.
Genre `Obtenir la note` ?

2023-03-23 10:44 UTC, hrenaud commented
@vvatelot et @jpkha j'ai géré la demande de mesure en deux temps, comme attendu par l'API/BFF
J'ai amélioré le design et je joins les captures d'écrans de presque tous les cas.

![SCR-20230323-fwi](https://user-images.githubusercontent.com/24810599/227179423-7a0221f9-29f5-4a01-868c-95d6540a531a.png)
![SCR-20230323-fx6](https://user-images.githubusercontent.com/24810599/227179429-2a809036-0fc3-41e5-a28a-9abe6226cb16.png)
![SCR-20230323-fxg](https://user-images.githubusercontent.com/24810599/227179433-f7566bca-e47d-43de-8bce-8ee8b8191bf3.png)
![SCR-20230323-fzb](https://user-images.githubusercontent.com/24810599/227179434-841a21dd-402a-40b8-8171-75cf5c11139b.png)
![SCR-20230323-fzl](https://user-images.githubusercontent.com/24810599/227179437-230fce9f-b2c9-42f4-b9ee-d73b207d5212.png)
![SCR-20230323-g07](https://user-images.githubusercontent.com/24810599/227179439-3d58cf99-abb8-4ac0-b4b4-43cebc5f67e2.png)


# warning
Les codes couleurs des badges SVG et les codes renvoyés par l'API/BFF ne sont pas cohérents

2023-04-08 08:38 UTC, jpkha approved these changes
juste une question et c'est bon pour moi

2023-04-08 08:38 UTC, jpkha commented on assets/js/ecoindex-badge.js
> +            await delay(15000);
15 second pour faire un appel ? Si c'est en cours de calcul tu attends 15 secondes avant de rappeler ?
C'est peut être un peu long non ?

2023-04-10 12:14 UTC, vvatelot commented
Hello, ce que je vous propose quand toutes les discussions seront closes c'est de créer une version 3 beta pour tester en réel. OK pour vous @hrenaud @jpkha ?

2023-04-12 10:06 UTC, JulienWilhelm commented
Quelques retours supplémentaires (sur cette PR si applicable, sinon au global) :

- Éviter le position fixed. Mieux vaut laisser à l'utilisateur le choix d'intégrer le badge à l'emplacement de son choix (typiquement, dans le footer),
- L'intitulé "Mesure en cours" souffre de problème de contraste,
- Revoir le title du bouton de résultat ("Analyse ecoindex", c'est trop léger, il faudrait plutôt quelque chose comme "Lors de sa dernière évaluation, cette page a obtenu un score ecoindex de X.").
- L'injection CSS est à revoir ; si pas d'analyse et demande d'analyse, il y aura doublon d'injection. Idéalement, il faudrait l'embarquer autrement qu'avec du JS (inline dans le div ?).

D'ailleurs, le point... _gênant_. Quid de l'utilité réelle du bouton de demande d'analyse, activable 1 seule fois ? Lors de l'intégration, il y a fort à parier que l'analyse aura déjà été faite ou qu'elle le sera (ce n'est clairement pas quelque chose que l'on veut faire porter sur l'utilisateur final). Je suis donc plutôt sceptique sur l'utilité au regard de la complexité que cela apporte. Il me paraissait préférable (et plus facile à faire embarquer) un badge qui se limite à donner l'information qu'on lui demande, et qui reste très léger, qu'un badge embarquant des fonctionnalités dont la plus value est discutable (à challenger, bien sûr !).

2023-04-12 13:49 UTC, hrenaud commented
> Quelques retours supplémentaires (sur cette PR si applicable, sinon au global) :
> 
> * Éviter le position fixed. Mieux vaut laisser à l'utilisateur le choix d'intégrer le badge à l'emplacement de son choix (typiquement, dans le footer),

C'est une position par défaut, pour éviter de se poser des questions à l'implémentation (je me mets à la place d'une personne non-développeur), de toute manière, ça s'override facilement en css. 

> * L'intitulé "Mesure en cours" souffre de problème de contraste,

@JulienWilhelm , parles au niveau du sens ou au niveau accessibilité ? J'ai réutilisé les couleurs en place, mais j'ai aussi remonté ce point sur les SVG. Je suis prêt à changer, mais il faut que toutes les solutions (svg et badge) soient cohérentes et soient cohérentes avec une charte graphique, s'il y en a une. Donc, dites-moi et je changerai.

> * Revoir le title du bouton de résultat ("Analyse ecoindex", c'est trop léger, il faudrait plutôt quelque chose comme "Lors de sa dernière évaluation, cette page a obtenu un score ecoindex de X.").

J'ai repris l'existant je pense.

> * L'injection CSS est à revoir ; si pas d'analyse et demande d'analyse, il y aura doublon d'injection. Idéalement, il faudrait l'embarquer autrement qu'avec du JS (inline dans le div ?).

Si l'on met du inline, c'est difficile de l'override en css. Par contre, je ne comprends pas le "doublon d'injection".

> D'ailleurs, le point... _gênant_. Quid de l'utilité réelle du bouton de demande d'analyse, activable 1 seule fois ? Lors de l'intégration, il y a fort à parier que l'analyse aura déjà été faite ou qu'elle le sera (ce n'est clairement pas quelque chose que l'on veut faire porter sur l'utilisateur final). Je suis donc plutôt sceptique sur l'utilité au regard de la complexité que cela apporte. Il me paraissait préférable (et plus facile à faire embarquer) un badge qui se limite à donner l'information qu'on lui demande, et qui reste très léger, qu'un badge embarquant des fonctionnalités dont la plus value est discutable (à challenger, bien sûr !).

L'objectif est de donner la main au visiteur de mesurer sans être obligé d'avoir l'extension du navigateur.  

Un site fait à la main, sans CMS sera facilement mesuré à la livraison. Avec un CMS, les pages se multipliant, il a fort à parier que les mesures ne soient plus faites, donc le visiteur peut le faire.
Après, il manque surement des cas d'usage comme de pouvoir lancer une nouvelle mesure, être informé que le nombre de mesures du jour est dépassé et de ce fait, cela sera impossible... Je te rejoins, le code doit rester léger, donc les fonctionnalités aussi, d'où ces "manques".

2023-04-12 13:52 UTC, hrenaud commented on assets/js/ecoindex-badge.js
> +            await delay(15000);
C'est ce que m'a dit de faire @vvatelot 🤷‍♂️ dites-moi

2023-04-13 13:18 UTC, JulienWilhelm commented
> C'est une position par défaut, pour éviter de se poser des questions à l'implémentation (je me mets à la place d'une personne non-développeur), de toute manière, ça s'override facilement en css.

L'override, plutôt que de décrire directement ce qui doit l'être, c'est une complexité supplémentaire du code :).

> @JulienWilhelm , tu parles au niveau du sens ou au niveau accessibilité ? J'ai réutilisé les couleurs en place, mais j'ai aussi remonté ce point sur les SVG. Je suis prêt à changer, mais il faut que toutes les solutions (svg et badge) soient cohérentes et soient cohérentes avec une charte graphique, s'il y en a une. Donc, dites-moi et je changerai.

Problème de contraste entre la couleur du texte temporaire et le fond.

> J'ai repris l'existant, je pense. Comme les titles ne sont pas visibles en mobile, je ne pense pas qu'il faille miser dessus pour informer les visiteurs.

On est d'accord, mais c'est toujours un petit plus appréciable.

> Si l'on met du inline, c'est difficile de l'override en css. Par contre, je ne comprends pas le "doublon d'injection".

Il me semble bien que la balise style est dupliquée entre le badge indéterminé, puis celui avec le score (elle apparait 2 fois dans le DOM). Sinon, pour l'inline, je vois ce que tu veux dire, mais il y a sûrement beaucoup de CSS commun que l'on pourrait mettre par défaut, puis injecter. Sinon, il me semble que l'on pourrait embarquer la balise <style> dans un parent. Qu'est-ce qui empêcherait de faire ceci, puis d'appliquer la bonne classe en JS ?

```
<div class="badge-container">
    <style>
        /* ... */
    </style>
    <!-- Badge HTML -->
</div>
```

> L'objectif est de donner la main au visiteur de mesurer sans être obligé d'avoir l'extension du navigateur.
> Un site fait à la main, sans CMS sera facilement mesuré à la livraison. Avec un CMS, les pages se multipliant, il a fort à parier que les mesures ne soient plus faites, donc le visiteur peut le faire.
Après, il manque surement des cas d'usage comme de pouvoir lancer une nouvelle mesure, être informé que le nombre de mesures du jour est dépassé et de ce fait, cela sera impossible... Je te rejoins, le code doit rester léger, donc les fonctionnalités aussi, d'où ces "manques".

Question de point de vue ; je persiste à croire que ce n'est pas à l'utilisateur final d'avoir le contrôle là-dessus. C'est le rôle de l'extension de Vincent, où cela se tient car le site n'est pas modifié après analyse, bien que cette dernière ait été menée.

2023-04-13 16:44 UTC, hrenaud commented
> Question de point de vue ; je persiste à croire que ce n'est pas à l'utilisateur final d'avoir le contrôle là-dessus. C'est le rôle de l'extension de Vincent, où cela se tient car le site n'est pas modifié après analyse, bien que cette dernière ait été menée.

Il faut trancher ce point. Si l'on part sur l'idée de ne pas laisser la main au visiteur, on laisse le code tel quel et l'on ferme cette MR.

Par contre,
- avec le script, l'utilisation des SVG peut être abandonné pour ne que faire du html. Ce seront des assets de moins à charger ;
- il faut peut-être modifier les titles comme tu le proposes ;
- Il faut mettre des contrastes accessibles sur les deux (html/js + SVG), car la solution de ne pas utiliser de javascript et recevoir une image est intéressante, d'où l'obligation de retravailler les SVG.

2023-04-18 10:19 UTC, JulienWilhelm commented
@hrenaud,

+1 pour le no-svg, si efficient,

Pour les autres fonctionnalités : à débattre (plus lourd et plus compliqué risque aussi de poser problème en terme d'adoption).

2023-09-06 01:45 UTC, closed without merging